version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: kura_db
    restart: always
    environment:
      POSTGRES_USER: kura_user
      POSTGRES_PASSWORD: kura_password
      POSTGRES_DB: kura_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
